### ISSUE TITLE
The website doesnt exists

### ISSUE THREAD

**Issue by BenHerbst** [Typhon0/AnimateFX#21]
### Description

I can't open the site of this project, 404 Not Found.

### Steps to Reproduce

Go on the site https://Typhon0.github.io/AnimateFX

### System Information (please complete the following information):
 - OS: Kubuntu 20.04
 - Java Version Not necessary
 - Version Not necessary

**Comment by nottirb** [comment]
It's worth mentioning that if you check /gh-pages there isn't anything other than a README.md

The API is located on javadoc and can be found here: https://javadoc.io/doc/io.github.typhon0/AnimateFX/latest/index.html

I would still leave this issue open since it's relevant.
