### ISSUE TITLE
No files were dowloaded

### ISSUE THREAD

**Issue by alexeyburak** [Typhon0/AnimateFX#23]
<img width="415" alt="Снимок экрана 2022-05-01 в 17 39 30" src="https://user-images.githubusercontent.com/88793366/166151012-2192b342-e956-470c-8b71-b7ae91d595a3.png">

- SDK: 11.0.12
- Maven

**Comment by Typhon0** [comment]
Hello, it should be available now on maven central repository.

https://repo1.maven.org/maven2/io/github/typhon0/AnimateFX/
